name: 'wiz-cli-ci-scan'
on:
  pull_request:
    branches:
    - main

jobs:
  wiz-cli-container-scan:
    if: contains(github.event.pull_request.head.ref, 'container')
    name: 'Wiz-cli Dockerfile and Container Scan'
    runs-on: ubuntu-latest
    env:
      # Set the relative path in the repo to scan
      SCAN_PATH_FAIL: "container"
      # Docker Image Info
      IMAGE: yanjar/cidemo
      TAG: ${{github.run_number}}
      # Set the desired Wiz-cli policies to use
      DIR_POLICY: "Jared-Yanna-Vuln,Jared-Yanna-Secrets"
      IAC_POLICY: "Jared-Yanna-IaC,Jared-Yanna-Secrets"
      VULN_POLICIES: "Jared-Yanna-Vuln,Jared-Yanna-Secrets"
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set path based on fail branch
      run: echo "SCAN_PATH=$SCAN_PATH_FAIL" >> $GITHUB_ENV
      if: contains(github.event.pull_request.head.ref, 'container')

    # Download and Authenticate to Wiz CLI
    - name: Download and Authenticate to Wiz
      run: |
        curl -o wizcli https://wizcli.app.wiz.io/latest/wizcli && chmod +x wizcli
        ./wizcli auth --id "$WIZ_CLIENT_ID" --secret "$WIZ_CLIENT_SECRET"
      env:
        WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
        WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}

    # Directory Scan
    - name: Run wiz-cli Dir scan
      id: wizcli-dir-scan
      run: ./wizcli dir scan --path ${{ env.SCAN_PATH }}  --policy "$DIR_POLICY" --output wiz-dir-scan-results.json,sarif,true

    # IaC Scan
    - name: Run wiz-cli IaC scan
      id: wizcli-iac-scan
      run: ./wizcli iac scan --path ${{ env.SCAN_PATH }} --policy "$IAC_POLICY" --output wiz-iac-scan-results.json,sarif,true --policy-hits-only

    # Docker Image Scan
    - name: Build the Docker image
      run: docker build ${{ env.SCAN_PATH }} -t $IMAGE:$TAG
      if: always()

    - name: Run wiz-cli Docker scan
      id: wizcli-docker-scan
      run: ./wizcli docker scan --image $IMAGE:$TAG --policy "$VULN_POLICIES" --policy-hits-only --dockerfile ${{ env.SCAN_PATH }}/Dockerfile --output wiz-image-scan-results.json,sarif,true

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Push docker image
      run: |
        docker push $IMAGE:$TAG
        echo "Pushing image here"

    - name: Run wiz-cli Docker tag
      run: |
        docker images list
        docker images --digests
        ./wizcli docker tag --image $IMAGE:$TAG